package com.cjhb.ssm.credit.system.entity.customer;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.CUSTOMERID
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.CUSTOMERNAME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String customername;
    private String encryptionkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.CUSTONMERABBRNAME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String custonmerabbrname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.CUSTOMERTYPE
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String customertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.CUSTOMERLEVEL
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String customerlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.RISKLEVEL
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String risklevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.OPENTIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private Date opentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.CLOSETIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private Date closetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.UPDATETIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecif.STATE
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.CUSTOMERID
     *
     * @return the value of ecif.CUSTOMERID
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.CUSTOMERID
     *
     * @param customerid the value for ecif.CUSTOMERID
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.CUSTOMERNAME
     *
     * @return the value of ecif.CUSTOMERNAME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.CUSTOMERNAME
     *
     * @param customername the value for ecif.CUSTOMERNAME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    public String getEncryptionkey() {
		return encryptionkey;
	}

	public void setEncryptionkey(String encryptionkey) {
		this.encryptionkey = encryptionkey;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.CUSTONMERABBRNAME
     *
     * @return the value of ecif.CUSTONMERABBRNAME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getCustonmerabbrname() {
        return custonmerabbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.CUSTONMERABBRNAME
     *
     * @param custonmerabbrname the value for ecif.CUSTONMERABBRNAME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setCustonmerabbrname(String custonmerabbrname) {
        this.custonmerabbrname = custonmerabbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.CUSTOMERTYPE
     *
     * @return the value of ecif.CUSTOMERTYPE
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getCustomertype() {
        return customertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.CUSTOMERTYPE
     *
     * @param customertype the value for ecif.CUSTOMERTYPE
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setCustomertype(String customertype) {
        this.customertype = customertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.CUSTOMERLEVEL
     *
     * @return the value of ecif.CUSTOMERLEVEL
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getCustomerlevel() {
        return customerlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.CUSTOMERLEVEL
     *
     * @param customerlevel the value for ecif.CUSTOMERLEVEL
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setCustomerlevel(String customerlevel) {
        this.customerlevel = customerlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.RISKLEVEL
     *
     * @return the value of ecif.RISKLEVEL
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getRisklevel() {
        return risklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.RISKLEVEL
     *
     * @param risklevel the value for ecif.RISKLEVEL
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setRisklevel(String risklevel) {
        this.risklevel = risklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.OPENTIME
     *
     * @return the value of ecif.OPENTIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public Date getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.OPENTIME
     *
     * @param opentime the value for ecif.OPENTIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setOpentime(Date opentime) {
        this.opentime = opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.CLOSETIME
     *
     * @return the value of ecif.CLOSETIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public Date getClosetime() {
        return closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.CLOSETIME
     *
     * @param closetime the value for ecif.CLOSETIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setClosetime(Date closetime) {
        this.closetime = closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.UPDATETIME
     *
     * @return the value of ecif.UPDATETIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.UPDATETIME
     *
     * @param updatetime the value for ecif.UPDATETIME
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecif.STATE
     *
     * @return the value of ecif.STATE
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecif.STATE
     *
     * @param state the value for ecif.STATE
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }
}