package com.cjhb.ssm.credit.system.dao.customer;

import java.util.List;
import java.util.Map;

import com.credit.entity.customer.Customer;
import com.credit.vo.customer.CustomerVO;

@SuppressWarnings("rawtypes")
public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecif
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    int deleteByPrimaryKey(String customerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecif
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    int insert(Customer customer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecif
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    int insertSelective(Customer customer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecif
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    Customer selectByPrimaryKey(String customerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecif
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    int updateByPrimaryKeySelective(Customer customer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecif
     *
     * @mbggenerated Mon Feb 22 21:43:48 CST 2016
     */
    int updateByPrimaryKey(Customer customer);
    
    List<CustomerVO> listByMap(Map<String, Object> map);
}